config/routes.rb
Signuper::Application.routes.draw do
  root 'site#index'

  devise_for :users, path: '', skip: [:registrations], path_names: {
    sign_in:      'login',
    sign_out:     'logout',
    registration: 'account',
    sign_up:      'register'
  },
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  as :user do
    get     '/account/cancel'   =>  'devise/registrations#cancel',  as: 'cancel_user_registration'
    post    '/account'          =>  'devise/registrations#create',  as: 'user_registration'
    get     '/account/register' =>  'devise/registrations#new',     as: 'new_user_registration'
    get     '/account/edit'     =>  'devise/registrations#edit',    as: 'edit_user_registration'
    patch   '/account'          =>  'devise/registrations#update'   
    delete  '/account'          =>  'devise/registrations#destroy'
  end

  get '/account' => 'account/dashboard#index', as: 'account_dashboard'

  namespace :account do
    resource  :profile, only: [:show, :edit, :update, :create]

    resources :event_options, path: 'events', only: [] do
      resource :registrations, only: [:create, :destroy] do
        get   'individual', on: :member
        get   'team', on: :member
      end
    end

    resources :registrations, only: [:index] do
      resources :transactions, only: [:new, :create, :destroy]
    end

    resources :transactions, only: [:index]
    resources :teams
    resources :participants, only: [:destroy]
    resource  :contacts, only: [:show, :edit, :create]
  end

  devise_for :managers, path_names: {
    sign_in:  'login',
    sign_out: 'logout'
  },
  skip: [:registrations] 

  as :manager do
    get     '/manager' =>  'devise/registrations#edit',  as: 'manager_registration'
    patch   '/manager' =>  'devise/registrations#update'   
  end

  namespace :manage do
    resources :events, except: [:destroy] do
      resources :prices, only: [:new, :create, :destroy]
      resources :registrations, only: [:new, :create]
      resource  :identification
      resources :event_options, path: 'options', except: [:show]
      resources :entries
    end

    resources :registrations, only: [:index, :show] do
      get 'approve', on: :member
      get 'revoke', on: :member
    end

    resources :users, except: [:destroy, :update]
    resources :transactions, only: [:update]
    resources :teams, only: [:index, :edit, :update, :destroy] 
    resources :categories
  end

  resources :events, only: [:show]
  resource :contacts, only: [:show, :edit, :create]
end

app/views/layouts/account.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : 'FamaRunners'

    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %meta{ name: 'msapplication-TileColor', content: '#2d2d2d' }
    %meta{ name: 'msapplication-TileImage', content: '/favfa.fa-144.png' }

    %link{ href: 'http://fonts.googleapis.com/css?family=Open+Sans:400,600', rel: 'stylesheet', type: 'text/css' }

    = stylesheet_link_tag "account", media: "all"
    = javascript_include_tag "application"

    %link{ rel: 'apple-touch-fa.fa', href: '/favfa.fa.png' }
    %link{ rel: 'fa.fa', href: '/favfa.fa.png' }

    /[if IE]
      %link{ rel: 'shortcut fa.fa', href: '/favfa.fa.ico' }

    = csrf_meta_tags

  %body
    .page
      .top-bar
        .inner
          %ul.top-nav
            %li
              = link_to destroy_user_session_path do
                %i.fa.fa-sign-out
                Sair
            %li
              = link_to account_contacts_path,
                class: ('active' if current_page_in?('account/contacts')) do
                %i.fa.fa-envelope
                Contactos
            %li
              = link_to edit_user_registration_path,
                class: ('active' if current_page_in?('devise/registrations')) do
                %i.fa.fa-cogs
                Conta
            %li
              = link_to account_profile_path,
                class: ('active' if current_page_in?('account/profiles')) do
                %i.fa.fa-user
                = current_user.name
      %nav.sidebar
        .powered-by.first
          = link_to root_path do
            = image_tag('account/logo.png')
        %ul.side-nav
          %li
            = link_to account_dashboard_path,
              class: ('active' if current_page_in?('account/dashboard')) do
              %i.fa.fa-dashboard
              Dashboard
          %li
            = link_to [:account, :teams],
              class: ('active' if current_page_in?('account/teams')) do
              %i.fa.fa-group
              Equipas
          %li
            = link_to [:account, :registrations],
              class: ('active' if current_page_in?('account/registrations')) do
              %i.fa.fa-inbox
              Inscrições
          %li
            = link_to [:account, :transactions],
              class: ('active' if current_page_in?('account/transactions')) do
              %i.fa.fa-eur
              Transações

      .main
        - if flash.any?
          - flash.each do |key, message|
            %div{ class: ['alert-box', key] }
              = message
              %a{ class: 'close' } &times;
        = yield

    - if Rails.env.production?
      = render 'shared/analytics'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : 'FamaRunners'

    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %meta{ name: 'msapplication-TileColor', content: '#2d2d2d' }
    %meta{ name: 'msapplication-TileImage', content: '/favicon-144.png' }

    %link{ href: 'http://fonts.googleapis.com/css?family=Open+Sans', rel: 'stylesheet', type: 'text/css' }

    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"

    %link{ rel: 'apple-touch-icon', href: '/favicon.png' }
    %link{ rel: 'favicon', href: '/favicon.png' }

    /[if IE]
      %link{ rel: 'shortcut icon', href: '/favicon.ico' }

    = csrf_meta_tags

%body
  #content-wrapper
    #nav-wrapper
      %nav.top-bar{ data: { topbar: '' } }
        %ul.title-area
          %li.name
            %h1
              = link_to 'Fama Runners', root_path
          %li.toggle-topbar.menu-icon
            = link_to '', '#'
        %section.top-bar-section
          %ul.right
            - if user_signed_in?
              %li
                = link_to [:account, :dashboard] do
                  %i.fa.fa-dashboard
                  Dashboard
              %li
                = link_to :contacts do
                  %i.fa.fa-envelope
                  Contactos
              %li
                = link_to destroy_user_session_path do
                  %i.fa.fa-sign-out
                  Sair
            - else
              %li
                = link_to new_user_session_path do
                  %i.fa.fa-sign-in
                  Login
              %li
                = link_to user_omniauth_authorize_path(:facebook),
                  title: 'Autenticar/Registar com Facebook' do
                  %i.fa.fa-sign-in
                  Facebook
              %li
                = link_to new_registration_path(:user) do
                  %i.fa.fa-user
                  Registar
              %li
                = link_to :contacts do
                  %i.fa.fa-envelope
                  Contactos


    %section.row
      .large-8.small-12.columns.feed
        = yield
      %aside.large-4.columns.hide-for-small
        .ui-side-box
          .ui-side-box-head
            %h5.title Redes Sociais
          .ui-side-box-body
            dee
        .ui-side-box
          .ui-side-box-head
            %h5.title Apoios
          .ui-side-box-body
            dee
    .push

  %footer
    .footer-inner.row
      .large-12.colums
        .contacts
          %h3.title Contactos
          %p
            %i.fa.fa-phone.fa-fw
            %span (+351) 252 374 845
            %br
            %i.fa.fa-mobile-phone.fa-fw
            %span (+351) 914 728 868
            %br
            %i.fa.fa-envelope.fa-fw
            %span geral@famarunners.com
            %br
            %span
              %i.fa.fa-facebook.fa-fw
              = link_to 'http://facebook.com/famarunners' do
                @FamaRunners

  - if Rails.env.production?
    = render 'shared/analytics'

app/views/layouts/manage-auth.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : 'FamaRunners'

    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %meta{ name: 'msapplication-TileColor', content: '#2d2d2d' }
    %meta{ name: 'msapplication-TileImage', content: '/favfa.fa-144.png' }

    %link{ href: 'http://fonts.googleapis.com/css?family=Open+Sans:400,600', rel: 'stylesheet', type: 'text/css' }

    = stylesheet_link_tag "manage", media: "all", debug: true
    = javascript_include_tag "application"

    %link{ rel: 'apple-touch-fa.fa', href: '/favfa.fa.png' }
    %link{ rel: 'fa.fa', href: '/favfa.fa.png' }

    /[if IE]
      %link{ rel: 'shortcut fa.fa', href: '/favfa.fa.ico' }

    = csrf_meta_tags

  %body.manager-auth
    - if flash.any?
      - flash.each do |key, message|
        %div{ class: ['alert-box', key] }
          = message
          %a{ class: 'close' } &times;
    .manager-login
      .inner
        = yield

app/views/layouts/manage.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : 'FamaRunners'

    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %meta{ name: 'msapplication-TileColor', content: '#2d2d2d' }
    %meta{ name: 'msapplication-TileImage', content: '/favfa.fa-144.png' }

    %link{ href: 'http://fonts.googleapis.com/css?family=Open+Sans:400,600', rel: 'stylesheet', type: 'text/css' }

    = stylesheet_link_tag "manage", media: "all"
    = javascript_include_tag "application"

    %link{ rel: 'apple-touch-fa.fa', href: '/favfa.fa.png' }
    %link{ rel: 'fa.fa', href: '/favfa.fa.png' }

    /[if IE]
      %link{ rel: 'shortcut fa.fa', href: '/favfa.fa.ico' }

    = csrf_meta_tags

  %body
    .page
      .top-bar
        .inner
          %ul.top-nav
            %li
              = link_to destroy_user_session_path do
                %i.fa.fa-sign-out
                Sair
            %li
              = link_to manager_registration_path,
                class: ('active' if current_page_in?('devise/registrations')) do
                %i.fa.fa-cogs
                Conta
      %nav.sidebar
        .powered-by.first
          = link_to root_path do
            = image_tag('account/logo.png')
        %ul.side-nav
          %li
            = link_to [:manage, :users],
              class: ('active' if current_page_in?('manage/users')) do
              %i.fa.fa-inbox
              Utilizadores
          %li
            = link_to [:manage, :categories],
              class: ('active' if current_page_in?('manage/categories')) do
              %i.fa.fa-folder-open
              Escalões
          %li
            = link_to [:manage, :teams],
              class: ('active' if current_page_in?('manage/teams')) do
              %i.fa.fa-group
              Equipas
          %li
            = link_to [:manage, :events],
              class: ('active' if current_page_in?('manage/events', 'manage/identifications')) do
              %i.fa.fa-group
              Eventos
          %li
            = link_to [:manage, :registrations],
              class: ('active' if current_page_in?('manage/registrations')) do
              %i.fa.fa-eur
              Inscrições

      .main
        - if flash.any?
          - flash.each do |key, message|
            %div{ class: ['alert-box', key] }
              = message
              %a{ class: 'close' } &times;
        = yield

    - if Rails.env.production?
      = render 'shared/analytics'